name: pre-commit-hooks
 
on:
    pull_request:
      branches: [ publish, staging ]
      types: [ opened, synchronize ]
 
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: pngquant